#!/usr/bin/env python3
"""Regression test for the two lint gates that are easy to revert by accident.

WHY THIS FILE EXISTS. Both gates below were written in a downstream vendored
copy of `lint.py`, and a later "sync tooling" commit copied THIS repo's older
`lint.py` over the hardened one, silently reverting both. The sync verified
itself by comparing lint ERROR COUNTS before and after, which were identical —
because the corpus had already been cleaned, so a demoted gate had nothing left
to fire on. A check whose corpus is clean cannot tell you it stopped checking.

So the gates get a behaviour test, upstream, in the repo that owns the linter:

  1. A file that does not declare `gmd:` is an ERROR, not a warning. As a
     warning it is the gate that cannot fail — an undeclared file is never
     parsed as GMD, so NONE of its anchors, wikilinks or `rel:` edges are
     checked, and docs drift out of the graph while lint reports success.
     Genuinely-flat files opt out IN THE FILE, with a reason.
  2. An UNCLOSED code fence is an ERROR. Everything after it parses as code, so
     every heading, anchor and edge below it silently stops existing — a
     formatting slip that DELETES graph nodes.

Stdlib only, no pytest: this runs in CI next to `lint-gmd.sh`, which is plain
bash and python3. Exits 0 when every case holds, 1 with a report otherwise.
"""
from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LINT = REPO / "lint.py"

VALID = (
    '---\n'
    'gmd: "0.1"\n'
    'id: sample\n'
    'title: "Sample"\n'
    'tags: [t]\n'
    '---\n'
    '\n'
    '# Sample {#root}\n'
    '\n'
    'Body.\n'
)

NO_FRONTMATTER = "# Sample\n\nJust markdown.\n"

NO_GMD_KEY = (
    '---\n'
    'id: sample\n'
    'title: "Sample"\n'
    'tags: [t]\n'
    '---\n'
    '\n'
    '# Sample {#root}\n'
)

OPT_OUT_WITH_REASON = (
    "<!-- not-gmd: flat one-line-per-entry index, regenerated by a tool -->\n"
    "# Index\n\n- [a](a.md)\n"
)

OPT_OUT_NO_REASON = "<!-- not-gmd: -->\n# Index\n\n- [a](a.md)\n"

OPT_OUT_ON_LINE_TWO = (
    "# Index\n"
    "<!-- not-gmd: too late, the marker has to be the first line -->\n"
)

UNCLOSED_FENCE = (
    '---\n'
    'gmd: "0.1"\n'
    'id: broken\n'
    'title: "Broken"\n'
    'tags: [t]\n'
    '---\n'
    '\n'
    '# Broken {#root}\n'
    '\n'
    '```\n'
    'fenced\n'
    '```\n'
    '\n'
    '```\n'
    '\n'
    '## Swallowed {#swallowed}\n'
    '\n'
    'text\n'
)

# (name, filename, content, must_fail, must_mention)
CASES = [
    ("a valid doc lints clean", "ok.md", VALID, False, ""),
    ("no frontmatter at all is an error", "bare.md", NO_FRONTMATTER, True,
     "no-gmd-version"),
    ("frontmatter without the gmd key is an error", "nokey.md", NO_GMD_KEY, True,
     "no-gmd-version"),
    ("the error says what is lost and how to opt out", "nokey2.md", NO_GMD_KEY,
     True, "not-gmd"),
    ("a reasoned opt-out passes", "INDEX.md", OPT_OUT_WITH_REASON, False, ""),
    ("an opt-out with no reason is an error", "noreason.md", OPT_OUT_NO_REASON,
     True, "not-gmd-no-reason"),
    ("the opt-out must be on line one", "late.md", OPT_OUT_ON_LINE_TWO, True,
     "no-gmd-version"),
    ("an unclosed fence is an error", "broken.md", UNCLOSED_FENCE, True,
     "unclosed-fence"),
    # MEMORY.md is GENERATED by its project's memory-index writer, which would
    # have to learn to emit the marker; it keeps a by-name exemption.
    ("MEMORY.md keeps its by-name exemption", "MEMORY.md", NO_FRONTMATTER,
     False, ""),
]


def run(path: Path) -> "tuple[int, str]":
    p = subprocess.run([sys.executable, str(LINT), str(path)],
                       capture_output=True, text=True)
    return p.returncode, p.stdout + p.stderr


def main() -> int:
    failures: list[str] = []
    with tempfile.TemporaryDirectory(prefix="gmdgates") as td:
        for name, fname, content, must_fail, must_mention in CASES:
            doc = Path(td) / fname
            doc.write_text(content)
            code, out = run(doc)
            failed = code != 0
            if failed != must_fail:
                failures.append(
                    f"{name}: expected {'an error' if must_fail else 'clean'}, "
                    f"got exit {code}\n{out.strip()}")
            elif must_mention and must_mention not in out:
                failures.append(
                    f"{name}: error does not mention {must_mention!r}\n{out.strip()}")
            doc.unlink()

    if failures:
        print(f"lint gates: {len(failures)} of {len(CASES)} FAILED\n")
        for f in failures:
            print(f"  - {f}\n")
        return 1
    print(f"lint gates: {len(CASES)} cases pass")
    return 0


if __name__ == "__main__":
    sys.exit(main())
